name: 编译 Termux-API v0.48 APK (未签名, ARMv7)

on:
  push:
    branches:
      - build-0.48

jobs:
  build:
    runs-on: ubuntu-latest # 这行是缩进 4 个空格

    steps:                     # 这行是缩进 4 个空格
      - name: 步骤 1: 检出代码 # 这行是缩进 6 个空格 (2个在 - 后面, 4个在 name: 前)
        uses: actions/checkout@v4 # 这行是缩进 8 个空格

      - name: 步骤 2: 设置 Java 开发环境 (JDK 17) # 缩进 6 个空格
        uses: actions/setup-java@v4 # 缩进 8 个空格
        with:                       # 缩进 8 个空格
          java-version: '17'        # 缩进 10 个空格
          distribution: 'temurin'   # 缩进 10 个空格
          cache: 'gradle'           # 缩进 10 个空格

      - name: 步骤 3: 授予 gradlew 执行权限 # 缩进 6 个空格
        run: chmod +x gradlew      # 缩进 8 个空格

      - name: 步骤 4: 构建针对 ARMv7 架构的发布版 APK (未签名) # 缩进 6 个空格
        run: ./gradlew assembleRelease # 缩进 8 个空格

      - name: 步骤 5: 上传构建产物 (APK 文件) # 缩进 6 个空格
        uses: actions/upload-artifact@v4 # 缩进 8 个空格
        with:                             # 缩进 8 个空格
          name: termux-api-v0.48-unsigned-apk # 缩进 10 个空格
          path: app/build/outputs/apk/release/app-release-unsigned.apk # 缩进 10 个空格
