# .github/workflows/debug_build.yml
name: 编译 Termux‑API v0.48 APK (未签名, ARMv7)

on:
  push:
    branches:
      - build-0.48          # 仅在这个分支推送时触发

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub 提供的 Ubuntu Runner

    steps:
      # 1. 检出代码
      - name: 检出代码
        uses: actions/checkout@v4

      # 2. 安装并缓存 JDK 17
      - name: 设置 JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 3. 赋予 gradlew 执行权限
      - name: 赋予 gradlew 执行权限
        run: chmod +x gradlew

      # 4. 编译 Release APK（未签名）
      - name: 编译 APK
        run: ./gradlew assembleRelease

      # 5. 上传 APK 构建产物
      - name: 上传 APK
        uses: actions/upload-artifact@v4
        with:
          name: termux-api-v0.48-unsigned-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
